### ISSUE TITLE
Notification width property

### ISSUE THREAD

**Issue by CatchABus** [keenethics/svelte-notifications#44]
**Is your feature request related to a problem? Please describe.**
Notification width cannot be increased even with a custom component.
The following rule affects outer div parent: `width: 270px;`
One must use global css rules to override default width and this is ugly.

**Describe the solution you'd like**
A width property to change notification size. It would be preferable using default styles while being able to adjust size.

**Comment by TylerRick** [comment]
I really want this as well.

The default hard-coded `width: 210px;` is very narrow, and without an easy way to make it wider, things can look very ugly with lines needlessly wrapping when there should be plenty of room to make it wider.

Here is an example, and it's not even one of the longer messages I may show:
![image](https://user-images.githubusercontent.com/14151/121401643-ce6deb00-c90d-11eb-8b0a-12f5b865ce99.png)

**Comment by rationalquality** [comment]
Okay, I'll work on it. I understand this problem. I would like to fix this so that it is possible to change the width of the notification using media-queries

Give me some time

**Comment by TylerRick** [comment]
Any update on this?

**Comment by TylerRick** [comment]
I was able to work around this for now with same global styles:

```css
.position-top-center.position-top-center.position-top-center {
  width: 650px;
}
.notification-content.notification-content.notification-content {
  width: 650px;
}
```
